services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
        - ./postgres_secrets.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow-kafka

volumes:
  postgres_data:
    driver: local

networks:
  airflow-kafka:
    external: true