services:
  spark-master:
    build: .
    ports:
      - "8088:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./jobs:/opt/spark-data
    networks:  
      - mb-py-kaf-spark-pg
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    build: .
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./jobs:/opt/spark-data
    networks:  
      - mb-py-kaf-spark-pg
networks:
  mb-py-kaf-spark-pg:
    external: true